heroes = [
    "Abaddon",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Arc Warden",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Bristleback",
    "Broodmother",
    "Centaur Warrunner",
    "Chaos Knight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Crystal Maiden",
    "Dark Seer",
    "Dark Willow",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Doom",
    "Dragon Knight",
    "Drow Ranger",
    "Earth Spirit",
    "Earthshaker",
    "Elder Titan",
    "Ember Spirit",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Grimstroke",
    "Gyrocopter",
    "Hoodwink",
    "Huskar",
    "Invoker",
    "Io",
    "Jakiro",
    "Juggernaut",
    "Keeper of the Light",
    "Kunkka",
    "Legion Commander",
    "Leshrac",
    "Lich",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycan",
    "Magnus",
    "Marci",
    "Mars",
    "Medusa",
    "Meepo",
    "Mirana",
    "Monkey King",
    "Morphling",
    "Muerta",
    "Naga Siren",
    "Nature's Prophet",
    "Necrophos",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Oracle",
    "Outworld Devourer",
    "Pangolier",
    "Phantom Assassin",
    "Phantom Lancer",
    "Phoenix",
    "Primal Beast",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Slardar",
    "Slark",
    "Snapfire",
    "Sniper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Techies",
    "Templar Assassin",
    "Terrorblade",
    "Tidehunter",
    "Timbersaw",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Troll Warlord",
    "Tusk",
    "Underlord",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Void Spirit",
    "Warlock",
    "Weaver",
    "Windranger",
    "Winter Wyvern",
    "Witch Doctor",
    "Wraith King",
    "Zeus"
]

url_heroes = [
    'Anti-Mage',
    'Axe',
    'Bane',
    'Bloodseeker',
    'Crystal_Maiden',
    'Drow_Ranger',
    'Earthshaker',
    'Juggernaut',
    'Mirana',
    'Morphling',
    'Shadow_Fiend',
    'Phantom_Lancer',
    'Puck',
    'Pudge',
    'Primal_Beast',
    'Razor',
    'Sand_King',
    'Storm_Spirit',
    'Sven',
    'Tiny',
    'Vengeful_Spirit',
    'Windranger',
    'Zeus',
    'Kunkka',
    'Lina',
    'Lion',
    'Shadow_Shaman',
    'Slardar',
    'Tidehunter',
    'Witch_Doctor',
    'Riki',
    'Enigma',
    'Tinker',
    'Sniper',
    'Necrophos',
    'Warlock',
    'Beastmaster',
    'Queen_of_Pain',
    'Venomancer',
    'Faceless_Void',
    'Wraith_King',
    'Death_Prophet',
    'Phantom_Assassin',
    'Pugna',
    'Templar_Assassin',
    'Viper',
    'Luna',
    'Dragon_Knight',
    'Dazzle',
    'Clockwerk',
    'Leshrac',
    'Nature%27s_Prophet',
    'Lifestealer',
    'Dark_Seer',
    'Clinkz',
    'Omniknight',
    'Enchantress',
    'Huskar',
    'Night_Stalker',
    'Broodmother',
    'Bounty_Hunter',
    'Weaver',
    'Jakiro',
    'Batrider',
    'Chen',
    'Spectre',
    'Ancient_Apparition',
    'Doom',
    'Ursa',
    'Spirit_Breaker',
    'Gyrocopter',
    'Alchemist',
    'Invoker',
    'Silencer',
    'Outworld_Devourer',
    'Lycan',
    'Brewmaster',
    'Shadow_Demon',
    'Lone_Druid',
    'Chaos_Knight',
    'Meepo',
    'Treant_Protector',
    'Ogre_Magi',
    'Undying',
    'Rubick',
    'Disruptor',
    'Nyx_Assassin',
    'Naga_Siren',
    'Keeper_of_the_Light',
    'Io',
    'Visage',
    'Slark',
    'Medusa',
    'Troll_Warlord',
    'Centaur_Warrunner',
    'Magnus',
    'Timbersaw',
    'Bristleback',
    'Tusk',
    'Skywrath_Mage',
    'Abaddon',
    'Elder_Titan',
    'Legion_Commander',
    'Techies',
    'Ember_Spirit',
    'Earth_Spirit',
    'Underlord',
    'Terrorblade',
    'Phoenix',
    'Oracle',
    'Winter_Wyvern',
    'Arc_Warden',
    'Monkey_King',
    'Dark_Willow',
    'Pangolier',
    'Grimstroke',
    'Mars',
    'Marci',
    'Muerta'
]
