items = [
    "Tango",
    "Healing Salve",
    "Clarity",
    "Smoke of Deceit",
    "Dust of Appearance",
    "Observer Ward",
    "Sentry Ward",
    "Gem of True Sight",
    "Town Portal Scroll",
    "Aegis of the Immortal",
    "Cheese",
    "Iron Branch",
    "Gauntlets of Strength",
    "Slippers of Agility",
    "Mantle of Intelligence",
    "Circlet",
    "Belt of Strength",
    "Band of Elvenskin",
    "Robe of the Magi",
    "Magic Wand",
    "Null Talisman",
    "Wraith Band",
    "Bracer",
    "Power Treads",
    "Phase Boots",
    "Boots of Travel",
    "Hand of Midas",
    "Arcane Boots",
    "Urn of Shadows",
    "Medallion of Courage",
    "Force Staff",
    "Glimmer Cape",
    "Eul's Scepter of Divinity",
    "Guardian Greaves",
    "Aether Lens",
    "Blink Dagger",
    "Veil of Discord",
    "Dagon",
    "Octarine Core",
    "Battle Fury",
    "Black King Bar",
    "Butterfly",
    "Desolator",
    "Daedalus",
    "Divine Rapier",
    "Monkey King Bar",
    "Satanic",
    "Vanguard",
    "Blade Mail",
    "Hood of Defiance",
    "Pipe of Insight",
    "Crimson Guard",
    "Assault Cuirass",
    "Heart of Tarrasque",
    "Mekansm",
    "Pipe of Insight",
    "Scythe of Vyse",
    "Lotus Orb",
    "Aghanim's Scepter",
    "Refresher Orb",
    "Shiva's Guard",
    "Bloodstone",
    "Abyssal Blade",
    "Hurricane Pike",
    "Silver Edge",
    "Aeon Disk",
    "Linken's Sphere",
    "Vladmir's Offering",
    "Eye of Skadi",
    "Spirit Vessel",
    "Ethereal Blade",
    "Skull Basher",
    "Shadow Blade",
    "Manta Style"
]
